### ISSUE TITLE
Firebase vs Supabase

### ISSUE THREAD

**Issue by dodger213** [dodger213/Ecommerce-Store---Next#69]
I want to add social login functionality on my Ecommerce store created by Nextjs.
But I am a little confused about Firebase and Supabase in their characteristics.
What is the difference between Firebase and Supbase?
Plz help me.

**Comment by stevenpiao0822** [comment]
Firebase and Suabase are both popular backend-as-a-service platforms that provide various features for building apps, including social login functionality.
I strongly suggest you to choose Firebase if you need a robust ecosystem with real-time capabilities and are comfortable with NoSQL databases, while Supabase if you prefer a relational database. 
I hope this will be a little bit help for you.
Regards.

**Comment by dodger213** [comment]
Thx. It would be a great help.
