### ISSUE TITLE
Login Functionality in development and production

### ISSUE THREAD

**Issue by dodger213** [dodger213/Ecommerce-Store---Next#70]
I have implemented Google OAuth2.0 for google login on my project, but it works well once I deployed but when I run on my local, Google auth said, the account is blocked.
Does anyone have experience in that?

**Comment by stevenpiao0822** [comment]
Plz check the authorized redirect url 
On your local: http://localhost:3000/api/auth/callback/google
sth like that

**Comment by dodger213** [comment]
Good. Thx
